/**
 * Webpack Configuration
 *
 * This configuration file is used by Webpack to bundle JavaScript files for usage in a browser.
 * It uses Node.js modules and should be run in a Node.js environment.
 *
 * @module webpack.config
 */

/**
 * @type {import('webpack').Configuration}
 * @property {string} entry - The entry point for the bundle process (relative to this config file).
 * @property {Object} output - Output configuration for the bundle.
 * @property {string} output.filename - The name of the output bundle file.
 * @property {string} output.path - The output directory as an absolute path.
 * @property {Object} module - Configuration regarding modules (loaders).
 * @property {Array} module.rules - Array of rules for how different file types should be handled.
 */

/**
 * Path module from Node.js to resolve directory paths.
 * @const
 */
const path = require('path');
const htmlPlugin = require('html-webpack-plugin');
const copyWebpackPlugin = require('html-webpack-plugin');
const MiniCssExtractPlugin = require("mini-css-extract-plugin");

module.exports = {
  /* 
    We can also create multiple entry points in our webpacks. Suppose we have created two html files
    One fiel is right now index.js and other can be explore.js & explore.html .
    Right now the entry point is from index.js. Now IF I want to add entry point for the explore.js file
    We need to set the entry property to an object where each key is a bundle name and each value is the path to the entry file. Webpack will generate separate bundles for each entry.

    entry: {
      main: './src/index.js',
      admin: './src/admin.js',
      vendor: './src/vendor.js'
    },
    output: {
      filename: '[name].bundle.js', // [name] will be replaced by 'main', 'explore', etc.
      path: path.resolve(__dirname, 'dist')
    },
  */
  entry: {
    main:'./src/index.js',
    explore:'./src/explore.js'
  },
  output: {
    filename: '[name].bundle.js',
    path: path.resolve(__dirname, 'dist'),

    /* 
      assetModuleFilename: controls the output path and filename for asset files handled by Webpack’s asset modules.
      This configuration will emit image files into a folder named images/ 
      with a unique hash in their filename, preserving their extension and query string. 

      [hash]: This is replaced with a unique hash value generated by Webpack based on the file’s content. 
      It helps with cache busting—when the file changes, the hash changes, so browsers know to download the new version.
      
      [query]: This is replaced with the resource’s query string, 
      if any (for example, if you import an image with a query like image.png?version=1.2, 
      [query] will be ?version=1.2).

      If you import logo.png?version=1.2, the output might be: images/abc123.png?version=1.2
    */
    assetModuleFilename: 'images/[hash][ext][query]',
    clean:true // keep dist folder clean removing unnecssary files
  },


  plugins: [
    new htmlPlugin({

      /* 
        template: Specifies the path to your custom HTML file (e.g., src/index.html). 
        The plugin uses this file as a base and injects the generated JS/CSS bundles into it. 
        If you don’t set template, it generates a default HTML file.


        chunks: An array specifying which entry point bundles to include in the generated HTML file. 
        For example, if you have multiple entry points (like main and explore), you can control 
        which bundles are injected into each HTML file by setting chunks: ['main'] or chunks: ['explore'].

      */
      template: './src/index.html',
      chunks: ["main"],
      filename: 'main.html',
      // inject:'body' where we want to inject the html in <head> or <body> tag.
    }),

    // Creating instacne for the explore html file. 
    new htmlPlugin({
      template: './src/explore.html',
      chunks: ["explore"],
      filename: 'explore.html'
    }),

    new MiniCssExtractPlugin(),
    new copyWebpackPlugin({
      patterns:[
        {
          from: path.resolve(__dirname, 'src/assets/perfume1.jpg'),
          to: path.resolve(__dirname, 'dist', 'assets/images')
        }
      ]
    })
  ],
  /**
   * Module configuration for handling different file types.
   * @type {Object}
   */
  module: {
    /**
     * Array of rules for module (file) processing.
     * @type {Array}
     */
    rules: [
      {
        /**
         * Regex to match image file extensions.
         * @type {RegExp}
         */
        test: /\.(jpg|jpeg|png|gif)$/i,
        /**
         * It is a loader for processing different types of files (images)
         * Specifies how the matched files will be processed.
         * 'asset/resource' emits a separate file and exports the URL.
         * @type {string}
         */
        type: 'asset/resource',
      },
      {
        test:/\.(css)$/i,
        use:[MiniCssExtractPlugin.loader, 'css-loader']
      },
      {
        test:/\.(scss)$/i,
        use: [MiniCssExtractPlugin.loader, 'css-loader', 'sass-loader']
      }
    ]
  }
}